apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: 443
      nodePort: {{ .Values.service.httpsNodePort }}
      protocol: TCP
  selector:
    app: nginx